import js from "@eslint/js";
import svelte from "eslint-plugin-svelte";
import ts from "typescript-eslint";

export default ts.config(
  js.configs.recommended,
  ts.configs.recommended,
  svelte.configs.recommended,
  {
    // The Svelte parser hands the contents of a `<script lang="ts">` block to
    // the TypeScript parser, which it does not pick up on its own.
    files: ["**/*.svelte", "**/*.svelte.ts"],
    languageOptions: { parserOptions: { parser: ts.parser } },
    rules: {
      // TypeScript resolves every name against the DOM lib and reports the
      // ones it cannot. This rule sees no lib at all and calls `document` a
      // typo. typescript-eslint turns it off for `.ts`; Svelte needs the same.
      "no-undef": "off",
    },
  },
  {
    // Generated by SvelteKit and Vite. Nothing here is written by hand.
    ignores: [".svelte-kit/", "build/"],
  },
);
