import js from "@eslint/js";
import { defineConfig, globalIgnores } from "eslint/config";
import svelte from "eslint-plugin-svelte";
import tseslint from "typescript-eslint";

export default defineConfig(
  // Generated by SvelteKit and Vite, or owned by an agent. Nothing here is
  // written by hand against this config.
  globalIgnores([".svelte-kit/", "build/", ".agents/", ".claude/"]),
  {
    // A suppression that no longer suppresses anything is a comment claiming a
    // problem that is gone.
    linterOptions: { reportUnusedDisableDirectives: "error" },
  },
  js.configs.recommended,
  tseslint.configs.strictTypeChecked,
  tseslint.configs.stylisticTypeChecked,
  svelte.configs.recommended,
  {
    // This config file is the only plain JavaScript in the project, and it is
    // outside the TypeScript program.
    files: ["**/*.js"],
    extends: [tseslint.configs.disableTypeChecked],
  },
  {
    // Type-aware rules need a program. `projectService` finds it from
    // tsconfig.json, which already includes the Svelte files.
    files: ["**/*.ts", "**/*.svelte", "**/*.svelte.ts"],
    languageOptions: {
      parserOptions: { projectService: true, extraFileExtensions: [".svelte"] },
    },
    rules: {
      // TypeScript resolves every name against the DOM lib and reports the ones
      // it cannot. This rule knows no lib and calls `document` a typo.
      "no-undef": "off",
      // The deck is a document: a type describes the shape of a slide's data,
      // and nothing here is meant to be reopened by a consumer.
      "@typescript-eslint/consistent-type-definitions": ["error", "type"],
      // A measurement in a string is what this project does all day.
      "@typescript-eslint/restrict-template-expressions": [
        "error",
        { allowNumber: true },
      ],
    },
  },
  {
    // The Svelte parser hands the contents of a `<script lang="ts">` block to
    // the TypeScript parser, which it does not pick up on its own.
    files: ["**/*.svelte", "**/*.svelte.ts"],
    languageOptions: { parserOptions: { parser: tseslint.parser } },
    rules: {
      // `onclick={() => dialog.close()}` is how Svelte binds a handler, and the
      // braces this rule asks for say nothing the arrow did not.
      "@typescript-eslint/no-confusing-void-expression": "off",
    },
  },
);
